### PR TITLE
Test if services can be retrieved from container via `$I->grabService`

### PR DESCRIPTION
**Pull request by burned42**
As already mentioned in https://github.com/Codeception/Codeception/pull/5706 this is adding some tests for the changes I introduced there.

@Naktibalda :)

### CODE REVIEW

**Comment by burned42** [comment]
I didn't notice that there's a CI in this project, too. It seems to use Codeception 2.5, so my added tests are expected to fail I guess, since 2.5 doesn't include the changes from above mentioned PR. How should we proceed with this? :confused:

**Comment by Naktibalda** [comment]
Composer.json is out of sync with composer.lock - commit updated composer.lock or modify .travis.yml to run composer update.

**Comment by burned42** [comment]
@Naktibalda Finally, after switching to `composer update`, deactivating the memory limit for that command and switching to the latest version of codeception (3.1 instead of 3.0) the CI succeeds. :smile:

**Comment by Naktibalda** [comment]
Thanks, I merged it.

**Pull request merged**
