### PR TITLE
Test deep association queries in Doctrine2::seeInRepository

### PR DESCRIPTION
**Pull request by alexkunin**
This pull request adds a test case for the fix discussed in Codeception/Codeception#5542.

### CODE REVIEW

**Review by Naktibalda — APPROVED** [review]
Looks good to me.
I will merge it tomorrow.

**Comment by Naktibalda** [comment]
I will run the tests now and if they don't work as expected, will rollback this change.

**Comment by alexkunin** [comment]
Well, I expect it to fail because it has a test case that exposes a bug in Codeception which is not fixed yet (since pull request in Codeception repo is not yet accepted).

**Comment by alexkunin** [comment]
Yep, in CI logs https://travis-ci.org/Codeception/symfony-demo/jobs/543789471 I see exception I was expecting: it is there because the test is executed against Codeception code without fix applied.

**Comment by Naktibalda** [comment]
Build of 3.0 branch has failed: https://travis-ci.org/Codeception/Codeception/jobs/543754343

```
1) CommentCest: Create comment
 Test  tests/functional/CommentCest.php:createComment
                                                                                                                                                                                                                                                                                                                                                   
  [TypeError] Argument 1 passed to Doctrine\Common\Persistence\Mapping\AbstractClassMetadataFactory::getRealClass() must be of the type string, null given, called in /home/travis/build/Codeception/Codeception/framework-tests/vendor/doctrine/persistence/lib/Doctrine/Common/Persistence/Mapping/AbstractClassMetadataFactory.php on line 165 
```

Build of pull request passed: https://travis-ci.org/Codeception/Codeception/jobs/543757125

**Pull request merged**
