### PR TITLE
Updated to use latest version of Symfony Demo app (1.3.4)

### PR DESCRIPTION
**Pull request by pgl**
Attempt made to merge in the latest changes from the official Symfony Demo app (https://github.com/symfony/demo).

### CODE REVIEW

**Comment by pgl** [comment]
Not sure why Travis failed. The error is:

`!!  Fatal error: Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "WebpackEncoreBundle" from namespace "Symfony\WebpackEncoreBundle".`

but `composer.json` [definitely has webpack listed](https://github.com/pgl/symfony-demo/blob/322def2d5eba2dec9f217ce962208f738c2dbb4a/composer.json#L33):

`        "symfony/webpack-encore-bundle": "^1.1",`

**Comment by pgl** [comment]
Builds passing finally. :)

**Comment by Naktibalda** [comment]
@pgl Thanks for this, I totally missed it.
I updated dependencies to Symfony 4.4 to get the build passing (Symfony security check was failing) and merged it using another pull request.
It would be great if you could update this app to Symfony 5.0.

**Comment by Naktibalda** [comment]
I upgraded myself at https://github.com/Codeception/symfony-demo/tree/symfony5

**Pull request merged**
